### ISSUE TITLE
Retrieving a Time class that has been to_s

### ISSUE THREAD

**Issue by catuss-a** [injixo/time_frame#22]
Hello,
I know you specified that TimeFrame doesnt support Date class, but I've encounter another issue with Time class that has been converted to a string:
I need in my app to send a date from a client, retrieve it server side, build a TimeFrame with it in order to compare it to another TimeFrame Built from a field in my db (TimeFrame.new(min: self.start, max: self.end). 
When Im retrieving my start/end date from the network I build a new TimeFrame this way : TimeFrame.new(min: params[:start], ....), params[:start] is a Time class converted with to_s. Which fails when in your gem: @max_float = @max.to_f (idk what to_f does. to_float?!). Anyway I was getting a false return when calling overlaps? method on these two time classes due to the duration == 0 even though max/min in both instances were equal.
My solution was just to pass Time.parse(params[:start]) when building new TimeFrame from a converted to string Time Class. (not a good way to do I suppose though)
-Axel (sorry for my english)

**Comment by catuss-a** [comment]
2.1.2 :090 > Time.parse(Time.now.to_s).to_f
 => 1424569460.0 
2.1.2 :091 > Time.now.to_f
 => 1424569465.9685457

**Comment by catuss-a** [comment]
2.1.2 :108 >  t = TimeFrame.new(min: Time.parse(Time.now.to_s), max: Time.parse((Time.now + 1.day).to_s))
 => 2015-02-22 02:50:16 +0100..2015-02-23 02:50:16 +0100 
2.1.2 :109 > t.duration / 60 / 60 
 => 24.0 
2.1.2 :110 > t = TimeFrame.new(min: Time.now, max: Time.now + 1.day)
 => 2015-02-22 02:50:35 +0100..2015-02-23 02:50:35 +0100 
2.1.2 :111 > t.duration / 60 / 60 
 => 24.000000001390777 

Apparently building a TimeFrame with Time.parse(string timestamp) is more accurate

**Comment by jzernisch** [comment]
I'm not sure whether I'm getting you right:
* What of course does not work, is feeding strings from your params hash into the `TimeFrame` constructor, you need to parse it into a `Time` or `TimeWithZone` object  (just like you did in your second comment). `TimeFrame` relies on a `to_f` ("to float") method for the boundaries internally, so strings would not work (because unless the string represents a valid float, `String#to_f` returns `0`)
* Regarding the accuracy you're talking about it your second comment: The thing is that in one of the 2 examples, you serialize your `Time` object into a string which is a loss of information (fractions of seconds get lost). But in like with floats, be careful when comparing `Time` objects that are constructed with `Time.now` for example (`Time.now == Time.now` returns `false`!)

**Comment by catuss-a** [comment]
Alright it's more clear now. So Converting a Time Object into a string leads to a loss of fractions of seconds.

Thanks for your feedback.
